[codes]
1 = "2024017422001-4"
2 = "2024017422002-2"
3 = "2024017422003-0"
4 = "2024017422004-9"
5 = "2024017422005-7"
6 = "2024017422006-5"
7 = "2024017422007-3"
8 = "2024017422008-1"
9 = "2024017422009-0"
10 = "2024017422010-3"
11 = "2024017422011-1"
12 = "2024017422012-0"
13 = "2024017422013-8"
14 = "2024017422014-6"
15 = "2024017422015-4"
16 = "2024017422016-2"
17 = "2024017422017-0"
18 = "2024017422018-9"
19 = "2024017422019-7"
20 = "2024017422020-0"
21 = "2024017422021-9"
22 = "2024017422022-7"
23 = "2024017422023-5"
24 = "2024017422024-3"
25 = "2024017422025-1"
26 = "2024017422026-0"
27 = "2024017422027-8"
28 = "2024017422028-6"
29 = "2024017422029-4"
30 = "2024017422030-8"
31 = "2024017422031-6"
32 = "2024017422032-4"
33 = "2024017422033-2"
34 = "2024017422034-0"
35 = "2024017422035-9"
36 = "2024017422036-7"
37 = "2024017422037-5"
38 = "2024017422038-3"
39 = "2024017422039-1"
40 = "2024017422040-5"
41 = "2024017422041-3"
42 = "2024017422042-1"
43 = "2024017422043-0"
44 = "2024017422044-8"
45 = "2024017422045-6"
46 = "2024017422046-4"
47 = "2024017422047-2"
48 = "2024017422048-0"
49 = "2024017422049-9"
50 = "2024017422050-2"
